name: aloha
version: 3.0.2
description: Bindings for the Aloha HTML5 editor. Allows text updating/reading etc from Dart.
homepage: https://github.com/shamblett/aloha
environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dev_dependencies:
  test: '^1.16.0-nullsafety.16'
  pedantic: '^1.10.0-nullsafety.3'
  pana: '^0.14.10'
  build_runner: '^1.11.0'
  build_test: '^1.3.4'
  build_web_compilers: '^2.16.0'

