name: aloha
version: 3.0.2
description: Bindings for the Aloha HTML5 editor. Allows text updating/reading etc from Dart.
homepage: https://github.com/shamblett/aloha
environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: '^1.14.2'
  pedantic: '^1.9.0'
  pana: '^0.13.5'
  build_runner: '^1.8.0'
  build_test: '^0.10.12+1'
  build_web_compilers: '^2.8.0'

