name: aloha
version: 2.0.1
author: S. Hamblett <steve.hamblett@linux.com>
description: Bindings for the Aloha HTML5 editor
homepage: https://github.com/shamblett/aloha
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://oscf.org.uk/dart/api/aloha/aloha.html
dev_dependencies:
  browser: any
  unittest: '>=0.9.0 <0.10.0'
