name: aloha
version: 3.0.1
description: Bindings for the Aloha HTML5 editor. Allows text updating/reading etc from Dart.
homepage: https://github.com/shamblett/aloha
environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: '^1.9.4'
  build_runner: '^1.7.2'
  build_test: '^0.10.10'
  build_web_compilers: '^2.7.1'

