name: aloha
version: 4.0.0
description: Bindings for the Aloha HTML5 editor. Allows text updating/reading etc from Dart.
homepage: https://github.com/shamblett/aloha
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: '^1.16.8'
  pedantic: '^1.11.0'
  build_runner: '^1.12.2'
  build_test: '^2.0.0'
  build_web_compilers: '^2.16.0'

